default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: quiqup_test_development

test:
  <<: *default
  database: quiqup_test_test

production:
  <<: *default
  database: quiqup_test_production
  username: quiqup_test
  password: <%= ENV['QUIQUP_TEST_DATABASE_PASSWORD'] %>
